In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataklubOlahraga2019.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Bola Voli' 1 1 1 1]
 ['Panahan' 2 2 2 2]
 ['Renang' 1 1 1 1]
 ['Sepak Bola' 165 168 168 170]
 ['Sepak Takraw' 1 1 1 1]
 ['Tenis' 23 23 23 23]
 ['Tinju Beladiri' 4 4 4 4]]


In [4]:
print(y)

[  1   2   1 170   1  23   4]


In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [6]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 1 1 1 1]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 2 2 2 2]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 1 1 1 1]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 165 168 168 170]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1 1 1 1]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 23 23 23 23]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 4 4 4 4]]


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
print(y)

[0 1 0 4 0 3 2]


In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [10]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 2 2 2 2]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1 1 1 1]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 1 1 1 1]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 165 168 168 170]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 23 23 23 23]]


In [11]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 4 4 4 4]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 1 1 1 1]]


In [12]:
print(y_train)

[1 0 0 4 3]


In [13]:
print(y_test)

[2 0]
